DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS recommendations;
DROP TABLE IF EXISTS banners;
DROP TABLE IF EXISTS merchant_reviews;
DROP TABLE IF EXISTS service_bookings;
DROP TABLE IF EXISTS merchant_services;
DROP TABLE IF EXISTS merchants;
DROP TABLE IF EXISTS service_categories;
DROP TABLE IF EXISTS shop_order_items;
DROP TABLE IF EXISTS shop_orders;
DROP TABLE IF EXISTS cart_items;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS product_categories;
DROP TABLE IF EXISTS post_comments;
DROP TABLE IF EXISTS community_posts;
DROP TABLE IF EXISTS pet_albums;
DROP TABLE IF EXISTS pet_weights;
DROP TABLE IF EXISTS pet_vaccines;
DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS adoption_applications;
DROP TABLE IF EXISTS adoption_pets;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    role VARCHAR(20) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    avatar_url VARCHAR(255),
    gender VARCHAR(20),
    status VARCHAR(20) NOT NULL,
    bio VARCHAR(255),
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE adoption_pets (
    id BIGINT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(20) NOT NULL,
    breed VARCHAR(50),
    gender VARCHAR(20),
    age_desc VARCHAR(50),
    city VARCHAR(50),
    health_status VARCHAR(100),
    personality VARCHAR(100),
    adoption_requirements VARCHAR(255),
    story VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    cover_url VARCHAR(255),
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE adoption_applications (
    id BIGINT PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    experience_desc VARCHAR(255) NOT NULL,
    living_condition_desc VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    review_remark VARCHAR(255),
    reviewed_by BIGINT,
    reviewed_at DATETIME,
    created_at DATETIME
);

CREATE TABLE pets (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(20) NOT NULL,
    breed VARCHAR(50),
    gender VARCHAR(20),
    birthday DATE,
    weight DECIMAL(10,2),
    avatar_url VARCHAR(255),
    description VARCHAR(255),
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE pet_vaccines (
    id BIGINT PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    vaccine_name VARCHAR(100) NOT NULL,
    vaccinated_at DATE NOT NULL,
    next_due_at DATE,
    remark VARCHAR(255),
    created_at DATETIME
);

CREATE TABLE pet_weights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    weight DECIMAL(10,2) NOT NULL,
    recorded_at DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pet_albums (
    id BIGINT PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    caption VARCHAR(255),
    created_at DATETIME
);

CREATE TABLE messages (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL,
    created_at DATETIME
);

CREATE TABLE banners (
    id BIGINT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    link_url VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    sort INT NOT NULL,
    created_by BIGINT,
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE recommendations (
    id BIGINT PRIMARY KEY,
    biz_type VARCHAR(30) NOT NULL,
    biz_id BIGINT NOT NULL,
    slot_code VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    sort INT NOT NULL,
    created_by BIGINT,
    created_at DATETIME
);

CREATE TABLE community_posts (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category VARCHAR(30) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    cover_url VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    review_remark VARCHAR(255),
    like_count INT NOT NULL,
    favorite_count INT NOT NULL,
    comment_count INT NOT NULL,
    published_at DATETIME,
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE post_comments (
    id BIGINT PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME
);

CREATE TABLE product_categories (
    id BIGINT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    pet_type VARCHAR(20),
    sort INT NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE products (
    id BIGINT PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    subtitle VARCHAR(255),
    image_url VARCHAR(255),
    price DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL,
    pet_type VARCHAR(20),
    status VARCHAR(20) NOT NULL,
    description VARCHAR(2000),
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE cart_items (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    checked BOOLEAN NOT NULL,
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE shop_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_no VARCHAR(50) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    pay_amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    receiver_name VARCHAR(50) NOT NULL,
    receiver_phone VARCHAR(20) NOT NULL,
    receiver_address VARCHAR(255) NOT NULL,
    remark VARCHAR(255),
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE shop_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    product_image_url VARCHAR(255),
    unit_price DECIMAL(10,2) NOT NULL,
    quantity INT NOT NULL,
    subtotal_amount DECIMAL(10,2) NOT NULL
);

CREATE TABLE service_categories (
    id BIGINT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    sort INT NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE merchants (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    district VARCHAR(50) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    business_hours VARCHAR(100),
    score DECIMAL(3,1) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE merchant_services (
    id BIGINT PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    duration_minutes INT,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME
);

CREATE TABLE service_bookings (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    merchant_id BIGINT NOT NULL,
    merchant_service_id BIGINT NOT NULL,
    booking_time DATETIME NOT NULL,
    contact_name VARCHAR(50) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    remark VARCHAR(255),
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE merchant_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    score INT NOT NULL,
    content VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_community_posts_status_like_published
    ON community_posts (status, like_count, published_at);
CREATE INDEX idx_adoption_pets_status_created
    ON adoption_pets (status, created_at);
CREATE INDEX idx_merchants_status_score
    ON merchants (status, score);
CREATE INDEX idx_service_bookings_merchant_service_time_status
    ON service_bookings (merchant_id, merchant_service_id, booking_time, status);
CREATE INDEX idx_products_status_created
    ON products (status, created_at);
